---
name: pipeline_schedules_with_tags
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/81476
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/354421
milestone: '14.9'
type: development
group: group::pipeline execution
default_enabled: true
