---
name: projects_build_artifacts_size_refresh_low
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/81306
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/356018
milestone: '14.9'
type: development
group: group::pipeline insights
default_enabled: false
