---
name: ukraine_support_tanuki
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82050
rollout_issue_url:
milestone: '14.9'
type: development
group: group::editor
default_enabled: false
