# Yamllint of CI-related yaml.
# This uses rules from project root `.yamllint`.
lint-yaml:
  extends:
    - .default-retry
    - .yaml-lint:rules
  image: pipelinecomponents/yamllint:latest
  stage: lint
  needs: []
  variables:
    LINT_PATHS: .gitlab-ci.yml .gitlab/ci lib/gitlab/ci/templates data/deprecations data/removals data/whats_new
  script:
    - yamllint --strict -f colored $LINT_PATHS
